.

diff --git a/devops_pipelines/azdo-ci-build-train.yml b/devops_pipelines/azdo-ci-build-train.yml
--- a/devops_pipelines/azdo-ci-build-train.yml
+++ b/devops_pipelines/azdo-ci-build-train.yml
@@ -26,13 +26,15 @@ stages:
     timeoutInMinutes: 0
     steps:
     - template: azdo-base-pipeline.yml
-    - script: |
-        # Invoke the Python building and publishing a training pipeline
-        python3 $(Build.SourcesDirectory)/ml_pipelines/${{ variables.BUILD_TRAIN_SCRIPT }}
-      failOnStderr: 'false'
-      env:
-        SP_APP_SECRET: '$(SP_APP_SECRET)'
+    - task: AzureCLI@1
       displayName: 'Publish Azure Machine Learning Pipeline'
+      inputs:
+        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+        scriptLocation: inlineScript
+        inlineScript: |
+          set -e # fail on error
+          # Invoke the Python building and publishing a training pipeline
+          python3 $(Build.SourcesDirectory)/ml_pipelines/${{ variables.BUILD_TRAIN_SCRIPT }}
 - stage: 'Trigger_AML_Pipeline'
   displayName: 'Train, evaluate, register model via previously published AML pipeline'
   jobs:
@@ -44,15 +46,17 @@ stages:
     container: mcr.microsoft.com/mlops/python:latest
     timeoutInMinutes: 0
     steps:
-    - script: |
-        pipeline_id_file=$(mktemp)
-        python $(Build.SourcesDirectory)/ml_pipelines/run_train_pipeline.py --output_pipeline_id_file "$pipeline_id_file"
-        echo "##vso[task.setvariable variable=AMLPIPELINEID;isOutput=true]$(cat $pipeline_id_file)"
-        rm "$pipeline_id_file"
-      name: 'getpipelineid'
-      displayName: 'Get Pipeline ID'
-      env:
-        SP_APP_SECRET: '$(SP_APP_SECRET)'
+    - task: AzureCLI@1
+      displayName: 'Run Azure ML Pipeline'
+      inputs:
+        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+        scriptLocation: inlineScript
+        inlineScript: |
+          set -e # fail on error
+          pipeline_id_file=$(mktemp)
+          python $(Build.SourcesDirectory)/ml_pipelines/run_train_pipeline.py --output_pipeline_id_file "$pipeline_id_file" --skip_train_execution
+          echo "##vso[task.setvariable variable=AMLPIPELINEID;isOutput=true]$(cat $pipeline_id_file)"
+          rm "$pipeline_id_file"
   - job: "Run_ML_Pipeline"
     dependsOn: "Get_Pipeline_ID"
     displayName: "Trigger ML Training Pipeline"
